### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by isrealllairdrop** [recitativonika/proxy-type-checker#1]
If I enter the same proxy, will it be duplicated in the residential.txt file?
meaning there are 2 same proxies

**Comment by recitativonika** [comment]
no. if the same proxy exists, it will not be duplicated

**Comment by isrealllairdrop** [comment]
> no. if the same proxy exists, it will not be duplicated

Thank you sir.

so I can enter the proxy that I have filtered into the residential. And I do not hesitate to overwrite the previous proxy

**Comment by recitativonika** [comment]
yes
